### ISSUE TITLE
Setup deployment previews

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#237]
Deployment previews allow you to preview changes made in a branch and share this preview via a URL.

Use cases for deployment previews:
- Involve design input in development process (Suggested by @marioharper)
- Release and document beta packages from feature branches, allowing consumers to test packages much sooner (Suggested by @GeorgeTaveras1231)

Suggestions:
- www.netlify.com

**Comment by marioharper** [comment]
What are we currently using to host http://docs.union.theknot.com?

**Comment by GeorgeTaveras1231** [comment]
@marioharper We are using AWS S3 + CloudFront

**Comment by GeorgeTaveras1231** [comment]
I looked into setting this up on my spare time but am having an issue. It seems that yarn is not able to install all dependencies in netlify's container:

```
8:01:58 PM: Build started
8:01:58 PM: Fetching cached dependencies
8:02:03 PM: Expected build cache - but failed to find it
8:02:03 PM: Failed to extract cache, continuing with build
8:02:03 PM: No cached dependencies found. Cloning fresh repo
8:02:03 PM: git clone git@github.com:xogroup/union
8:02:09 PM: git remote rm origin
8:02:10 PM: Preparing Git Reference refs/heads/chore/setup-netlify
8:02:16 PM: Running build command: yarn setup.docs
8:02:19 PM: Downloading https://nodejs.org/dist/v8.0.0/node-v8.0.0-linux-x64.tar.xz...
# Omitted
8:02:50 PM:     0     0   3130      0 --:--:-- --:--:-- --:--:--  3130gpg: Signature made Sat 17 Dec 2016 12:30:28 PM UTC using RSA key ID FD2497F5gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"gpg: WARNING: This key is not certified with a trusted signature!gpg:          There is no indication that the signature belongs to the owner.Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310     Subkey fingerprint: 6A01 0C51 6600 6599 AA17  F081 46C2 130D FD24 97F5
8:02:51 PM: > Verifying integrity...
8:02:51 PM: > GPG signature looks good> Extracting to ~/.yarn...> Adding to $PATH...> We've added the following to your /opt/buildhome/.profile> If this isn't the profile of your current shell then please add the following to your correct profile:   export PATH="$HOME/.yarn/bin:$PATH"> Successfully installed Yarn 0.18.1! Please open another terminal where the `yarn` command will now be available.Installing NPM modules using Yarn version 0.18.1yarn install v0.18.1
8:02:51 PM: warning @xo-union/union@0.0.1: "dependencies" has dependency "pascal-case" with range "^2.0.1" that collides with a dependency in "devDependencies" of the same name with version "^2.0.0"
8:02:51 PM: [1/4] Resolving packages...
8:02:51 PM: [2/4] Fetching packages...
8:03:23 PM: warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
8:03:23 PM: info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
8:03:23 PM: [3/4] Linking dependencies...
8:03:23 PM: warning Incorrect peer dependency "webpack@^2.2.0".
8:03:23 PM: warning Incorrect peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0".
8:03:23 PM: warning Incorrect peer dependency "react-docgen@2.9.1".
8:03:23 PM: warning Unmet peer dependency "svgo@>=0.4.0".
8:03:23 PM: warning Incorrect peer dependency "webpack@^2.2.0".
8:03:23 PM: warning Incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
8:03:37 PM: [4/4] Building fresh packages...
8:03:37 PM: Done in 66.58s.
8:03:37 PM: NPM modules installed using Yarn
8:03:38 PM: yarn setup.docs v0.18.1
8:03:38 PM: $ yarn clean.public && yarn setup && yarn build.docs
8:03:38 PM: yarn clean.public v0.18.1
8:03:38 PM: $ git clean -dfx public/
8:03:38 PM: Done in 0.08s.
8:03:38 PM: yarn setup v0.18.1
8:03:38 PM: $ yarn install && yarn run bootstrap && yarn run build.patterns
8:03:39 PM: yarn install v0.18.1
8:03:39 PM: warning @xo-union/union@0.0.1: "dependencies" has dependency "pascal-case" with range "^2.0.1" that collides with a dependency in "devDependencies" of the same name with version "^2.0.0"
8:03:39 PM: [1/4] Resolving packages...
8:03:40 PM: [2/4] Fetching packages...
8:04:19 PM: warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
8:04:19 PM: info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
8:04:19 PM: [3/4] Linking dependencies...
8:04:19 PM: warning Incorrect peer dependency "webpack@^2.2.0".
8:04:19 PM: warning Incorrect peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0".
8:04:19 PM: warning Incorrect peer dependency "react-docgen@2.9.1".
8:04:19 PM: warning Unmet peer dependency "svgo@>=0.4.0".
8:04:19 PM: warning Incorrect peer dependency "webpack@^2.2.0".
8:04:20 PM: warning Incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
8:04:23 PM: [4/4] Building fresh packages...
8:04:23 PM: Done in 44.27s.
8:04:23 PM: yarn run v0.18.1
8:04:23 PM: $ lerna bootstrap --hoist && npm link ./packages/xojs
8:04:23 PM: module.js:487    throw err;    ^Error: Cannot find module 'dedent'    at Function.Module._resolveFilename (module.js:485:15)    at Function.Module._load (module.js:437:25)    at Module.require (module.js:513:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (/opt/buildhome/.cache/yarn/npm-lerna-2.0.0-rc.5-b59d168caaac6e3443078c1bce194208c9aa3090/lib/cli.js:8:15)    at Module._compile (module.js:569:30)    at Object.Module._extensions..js (module.js:580:10)    at Module.load (module.js:503:32)    at tryModuleLoad (module.js:466:12)    at Function.Module._load (module.js:458:3)
8:04:23 PM: error Command failed with exit code 1.
8:04:23 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
8:04:24 PM: error Command failed with exit code 1.
8:04:24 PM: error Command failed with exit code 1.
8:04:24 PM: Cached NPM modules
8:04:24 PM: Saved Yarn cache
8:04:25 PM: Build complete: exit code: 1
8:04:25 PM: Cleaning up docker container
8:04:26 PM: Error running command: Build script returned non-zero exit code: 1
8:04:27 PM: An error occurred while building the site, skipping the deploy and cache refresh.
8:04:27 PM: Build script returned non-zero exit code: 1
8:04:29 PM: Finished processing build request in 2m31.034162557s
```

**Comment by marioharper** [comment]
Can you add me to the netlify group? Maybe I can take a look at it if I get some time.

**Comment by GeorgeTaveras1231** [comment]
Great job on this @marioharper
